# Generated by Django 4.2.16 on 2024-09-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehospital_app', '0002_alter_doctor_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(default=1234, max_length=12),
            preserve_default=False,
        ),
    ]
