# Generated by Django 4.2.16 on 2024-09-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehospital_app', '0003_alter_doctor_mobile_alter_patient_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('cpassword', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='disease',
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
    ]
