# Generated by Django 4.2.16 on 2024-09-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehospital_app', '0006_patient_prescribtion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='prescribtion',
            new_name='prescription',
        ),
    ]
