# Generated by Django 4.2.16 on 2024-09-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehospital_app', '0007_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='prescription',
        ),
    ]
