# Generated by Django 4.2.16 on 2024-09-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehospital_app', '0009_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='cpassword',
        ),
        migrations.RemoveField(
            model_name='register',
            name='password',
        ),
        migrations.RemoveField(
            model_name='register',
            name='username',
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
