# Generated by Django 4.2.16 on 2024-09-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehospital_app', '0010_remove_register_cpassword_remove_register_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=366),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(default=1234, max_length=3),
            preserve_default=False,
        ),
    ]
